# Introduction

Flow in headwater (wadeable) streams is not well understood because most USGS gages target larger streams and rivers, because there are so many smaller streams and because it is expensive to collect flow data using traditional methods. With the explosion of AI/ML approaches in science, we now have the opportunity to use imagery to estimate flow in streams - see the [Flow Photos Explorer](https://www.usgs.gov/apps/ecosheds/fpe/#/). FPE is a combined database and modeling system which uses machine learning to estimate the distribution of relative flows among all the images for a site. The cumulative distribution of relative flows provides a ranking of all the images and also gives the shape of the relative flow duration curve. This can be valuable information by itself, but often practitioners will need estimates of absolute flow (e.g. m^3^s^-1^).

Here, we explore the empirical cumulative distribution curves (ECDC) of relative flow for several sites from FPE and, for sites with known flows estimated using the traditional approach, we compare the image-based ECDC to absolute flow ECDC and evaluate how well some small number of absolute flow estimates can approximate the entire ECDC and whether we can use these estimates to convert the image-based ECDC to an absolute flow ECDC.
